name: Snyk Intregation
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@0.3.0
        with:
          # Which Snyk command to run, defaults to test
          command: test wizard# optional, default is test
        env:
          SNYK_TOKEN: ${{ secrets.TOKEN }}
