name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.TOKEN }}
     
      - name: Login 
        uses: atlassian/gajira-login@master
        if: failure()
        env:
         JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
         JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
         JIRA_API_TOKEN: ${{ secrets.JIRA_API }}

      - name: Find Issue Key
        uses: ./
        if: failure()
        with:
         project: github error
         issuetype: bug
         messages: ERROR! 
       
 
      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: failure()
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "In Progress"
