name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.TOKEN }}
     
      - name: Login to Jira
        uses: atlassian/gajira-login@master
        if: failure()
        env:
         JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
         JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
         JIRA_API_TOKEN: ${{ secrets.JIRA_API }}
         
      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: failure()
        with:
          issue: bug
          transition: "In Progress" 
