name: npm audit

on:
  push:
    branches:
      - npm-audit
# on:
#   schedule:
#     - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm i
      - uses: oke-py/npm-audit-action@v1.8.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.TOKEN_OF_GITHUB }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
