name: npm audit

on:
  push:
    branches:
      - npm-audit
# on:
#   schedule:
#     - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install --save lodash@4.17.5
      - uses: oke-py/npm-audit-action@v1.8.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.TOKEN_OF_GITHUB }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          run: npm audit fix --force
          
      - name: Login to Jira
        uses: atlassian/gajira-login@master
        if: failure()
        env:
         JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
         JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
         JIRA_API_TOKEN: ${{ secrets.JIRA_API }}
         
      - name: Notify issue
        uses: atlassian/gajira-create@master
        if: failure()
        with:
          project: GE
          issuetype: Bug
          summary: Congratulations! ${{ github.workflow }} failed in ${{ github.repository }}
          pipeline-id: ${{ github.repository }} && ${{ github.workflow }}
          build-number: ${{ github.run_number }}
          build-state: "${{ env.BUILD_STATE }}"
          build-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
  
